# Generated by Django 3.2.4 on 2021-06-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='tags',
            field=models.ManyToManyField(to='memory_api.Tag'),
        ),
    ]
